### PR TITLE
HashKey编译不过

### PR DESCRIPTION
**Pull request by qmarliu**
在返回值的类型上加上foolgo的作用域就可以了。

### CODE REVIEW

**Comment by chncwang** [comment]
请问你用的是什么编译器？它就写在foolgo作用域内，为啥还要加foolgo呢

**Comment by qmarliu** [comment]
编译器版本是：gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) [g++也是这个版本]
以下的编译错误信息：
[  4%] Building CXX object CMakeFiles/foolgo.dir/src/foolishgo.cc.o
In file included from /home/liul/Documents/FoolGo/src/game/../player/player.h:4:0,
                 from /home/liul/Documents/FoolGo/src/game/fresh_game.h:9,
                 from /home/liul/Documents/FoolGo/src/foolishgo.cc:8:
/home/liul/Documents/FoolGo/src/game/../player/../board/full_board.h:85:3: error: declaration of ‘foolgo::HashKey foolgo::board::FullBoard<BOARD_LEN>::HashKey() const’ [-fpermissive]
   }
   ^
In file included from /home/liul/Documents/FoolGo/src/board/zob_hasher.h:6:0,
                 from /home/liul/Documents/FoolGo/src/foolishgo.cc:6:
/home/liul/Documents/FoolGo/src/board/../def.h:22:18: error: changes meaning of ‘HashKey’ from ‘typedef uint32_t foolgo::HashKey’ [-fpermissive]
 typedef uint32_t HashKey;
                  ^
CMakeFiles/foolgo.dir/build.make:62: recipe for target 'CMakeFiles/foolgo.dir/src/foolishgo.cc.o' failed

如果是在foolgo作用域内，为什么声明FullBoard的私有成员hash_key_需要加foolgo作用域：

**Comment by qmarliu** [comment]
编译器版本是：gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) [g++也是这个版本]
以下的编译错误信息：
[ 4%] Building CXX object CMakeFiles/foolgo.dir/src/foolishgo.cc.o
In file included from /home/liul/Documents/FoolGo/src/game/../player/player.h:4:0,
from /home/liul/Documents/FoolGo/src/game/fresh_game.h:9,
from /home/liul/Documents/FoolGo/src/foolishgo.cc:8:
/home/liul/Documents/FoolGo/src/game/../player/../board/full_board.h:85:3: error: declaration of ‘foolgo::HashKey foolgo::board::FullBoard<BOARD_LEN>::HashKey() const’ [-fpermissive]
}
^
In file included from /home/liul/Documents/FoolGo/src/board/zob_hasher.h:6:0,
from /home/liul/Documents/FoolGo/src/foolishgo.cc:6:
/home/liul/Documents/FoolGo/src/board/../def.h:22:18: error: changes meaning of ‘HashKey’ from ‘typedef uint32_t foolgo::HashKey’ [-fpermissive]
typedef uint32_t HashKey;
^
CMakeFiles/foolgo.dir/build.make:62: recipe for target 'CMakeFiles/foolgo.dir/src/foolishgo.cc.o' failed

如果是在foolgo作用域内，为什么声明FullBoard的私有成员hash_key_需要加foolgo作用域：
foolgo::HashKey hash_key_;

如果去掉foolgo同样也会报错，但两个都加上则编译通过。

**Comment by chncwang** [comment]
好的，谢谢！

**Pull request merged**
